"chats_ids": ["836078633776709663"]  # id чата. Брать из https://discord.com/channels/{id канала}/{id чата}
"token": "ABOBA"  # токен авторизации аккаунта
"lap_time_sleep": 10  # время задержки круга в секундах
"step_time_sleep": 1  # время задержки шага в секундах